version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: anka-tech-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - anka-network

  backend:
    build: .
    container_name: anka-tech-backend
    depends_on:
      - db
    ports:
      - "3333:3333"
    env_file:
      - .env
    volumes:
      - .:/projeto-anka-tech
      - /projeto-anka-tech/node_modules
    command: sh ./start.sh
    networks:
      - anka-network

volumes:
  db_data:

networks:
  anka-network:
    driver: bridge
